### ISSUE TITLE
Git Inspector bug

### ISSUE THREAD

**Issue by thomasathul** [thomasathul/STEPin_MiniProject#3]
Git inspector had been passing successfully last 4 days, this bug has suddenly occured yesterday.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/runner/gitinspector/gitinspector/changes.py", line 151, in run
    bisect.insort(commits, commit)
  File "/home/runner/gitinspector/gitinspector/changes.py", line 82, in __lt__
    return self.timestamp.__lt__(other.timestamp) # only used for sorting; we just consider the timestamp.
AttributeError: 'Commit' object has no attribute 'timestamp'
```

**Comment by thomasathul** [comment]
Going to delete all the workflows and remake them.

**Comment by thomasathul** [comment]
Removing git inspector from the workflow.

**Comment by thomasathul** [comment]
Possible solution- Try not to commit small changes to the main branch. The repository already has 200 commits. First, create a branch from the main/master and push all the small and big changes into the branch. When finally ready to deploy, push the branch to the main/master branch. 

"This can be caused by some logic error in the threading code" - gitinspector maintainer

**Comment by thomasathul** [comment]
Closing the issue
